export interface Product {
  id: string;
  name: string;
  nameHi: string;
  nameTe: string;
  price: number;
  image: string;
  category: string;
  eco: boolean;
  description: string;
  descriptionHi: string;
  descriptionTe: string;
}

export interface Order {
  id: string;
  items: { product: Product; qty: number }[];
  total: number;
  date: string;
  status: "pending" | "delivered" | "in-transit";
}

export interface CartItem {
  product: Product;
  qty: number;
  /** Catalog variant (for GST invoice) */
  variantId?: string;
  variantLabel?: string;
  /** Price in paise when from catalog; else derived from product.price * 100 */
  pricePaise?: number;
  gstRate?: number;
  mrpPaise?: number;
}

export const products: Product[] = [
  { id: "1", name: "Paper Plates (100 pcs)", nameHi: "पेपर प्लेट (100)", nameTe: "పేపర్ ప్లేట్లు (100)", price: 99, image: "🍽️", category: "Disposables", eco: true, description: "Biodegradable paper plates, perfect for street food serving.", descriptionHi: "बायोडिग्रेडेबल पेपर प्लेट, स्ट्रीट फूड सर्विंग के लिए बढ़िया।", descriptionTe: "బయోడిగ్రేడబుల్ పేపర్ ప్లేట్లు, వీధి ఫుడ్ సర్వింగ్‌కు అనువైనవి." },
  { id: "2", name: "Matchbox Pack (10)", nameHi: "माचिस पैक (10)", nameTe: "అగ్గిపెట్టె ప్యాక్ (10)", price: 30, image: "🔥", category: "Essentials", eco: false, description: "Standard safety matches, 10 boxes per pack.", descriptionHi: "स्टैंडर्ड सेफ्टी माचिस, 10 बॉक्स प्रति पैक।", descriptionTe: "స్టాండర్డ్ సేఫ్టీ అగ్గిపెట్టెలు, ప్యాక్‌కు 10 బాక్స్లు." },
  { id: "3", name: "Water Bottles Case (24)", nameHi: "पानी बोतल केस (24)", nameTe: "నీటి బాటిళ్ల కేస్ (24)", price: 240, image: "💧", category: "Essentials", eco: false, description: "500ml drinking water bottles, 24 per case.", descriptionHi: "500ml पीने का पानी बोतलें, 24 प्रति केस।", descriptionTe: "500ml తాగే నీటి బాటిళ్లు, కేస్‌కు 24." },
  { id: "4", name: "Paper Cups (200 pcs)", nameHi: "पेपर कप (200)", nameTe: "పేపర్ కప్పులు (200)", price: 150, image: "☕", category: "Disposables", eco: true, description: "Eco-friendly paper cups for hot beverages.", descriptionHi: "गर्म पेय के लिए इको-फ्रेंडली पेपर कप।", descriptionTe: "వేడి పానీయాలకు పర్యావరణ స్నేహపరమైన పేపర్ కప్పులు." },
  { id: "5", name: "Plastic Spoons (100)", nameHi: "प्लास्टिक चम्मच (100)", nameTe: "ప్లాస్టిక్ స్పూన్లు (100)", price: 60, image: "🥄", category: "Disposables", eco: false, description: "Sturdy disposable spoons, 100 per pack.", descriptionHi: "मजबूत डिस्पोजेबल चम्मच, 100 प्रति पैक।", descriptionTe: "గట్టి డిస్పోజబుల్ స్పూన్లు, ప్యాక్‌కు 100." },
  { id: "6", name: "Napkins Bundle (500)", nameHi: "नैपकिन बंडल (500)", nameTe: "నాప్కిన్ల బండిల్ (500)", price: 120, image: "🧻", category: "Essentials", eco: true, description: "Soft tissue napkins, bulk pack of 500.", descriptionHi: "सॉफ्ट टिश्यू नैपकिन, 500 का बल्क पैक।", descriptionTe: "సాఫ్ట్ టిష్యూ నాప్కిన్లు, 500 బల్క్ ప్యాక్." },
  { id: "7", name: "Tea Powder (1kg)", nameHi: "चाय पाउडर (1kg)", nameTe: "టీ పొడి (1kg)", price: 320, image: "🍵", category: "Essentials", eco: false, description: "Premium CTC tea powder, 1kg pack.", descriptionHi: "प्रीमियम CTC चाय पाउडर, 1kg पैक।", descriptionTe: "ప్రీమియం CTC టీ పొడి, 1kg ప్యాక్." },
  { id: "8", name: "Sugar (5kg)", nameHi: "चीनी (5kg)", nameTe: "చక్కెర (5kg)", price: 250, image: "🍬", category: "Essentials", eco: false, description: "Refined sugar, 5kg bag.", descriptionHi: "रिफाइंड चीनी, 5kg बैग।", descriptionTe: "రిఫైన్డ్ చక్కెర, 5kg బ్యాగ్." },
  { id: "9", name: "Panipuri Kit", nameHi: "पानीपुरी किट", nameTe: "పానీపూరీ కిట్", price: 500, image: "🎪", category: "Kits", eco: false, description: "Complete panipuri starter kit: plates + cups + napkins + water.", descriptionHi: "कंप्लीट पानीपुरी स्टार्टर किट: प्लेट + कप + नैपकिन + पानी।", descriptionTe: "పూర్తి పానీపూరీ స్టార్టర్ కిట్: ప్లేట్లు + కప్పులు + నాప్కిన్లు + నీరు." },
  { id: "10", name: "Eco Serve Bundle", nameHi: "इको सर्व बंडल", nameTe: "ఎకో సర్వ్ బండిల్", price: 399, image: "🌿", category: "Kits", eco: true, description: "All eco-friendly: biodegradable plates, cups, and napkins.", descriptionHi: "ऑल इको-फ्रेंडली: बायोडिग्रेडेबल प्लेट, कप और नैपकिन।", descriptionTe: "అన్నీ పర్యావరణ స్నేహపరం: బయోడిగ్రేడబుల్ ప్లేట్లు, కప్పులు మరియు నాప్కిన్లు." },
];

export const sampleOrders: Order[] = [
  { id: "ORD-1001", items: [{ product: products[0], qty: 3 }, { product: products[3], qty: 2 }], total: 597, date: "2026-02-15", status: "delivered" },
  { id: "ORD-1002", items: [{ product: products[8], qty: 2 }, { product: products[2], qty: 1 }], total: 1240, date: "2026-02-14", status: "in-transit" },
  { id: "ORD-1003", items: [{ product: products[6], qty: 1 }], total: 320, date: "2026-02-13", status: "delivered" },
  { id: "ORD-1004", items: [{ product: products[1], qty: 5 }, { product: products[5], qty: 2 }], total: 390, date: "2026-02-12", status: "delivered" },
];

export const vendorProfile = {
  name: "Raju",
  stallType: "Tea Stall",
  stallIcon: "☕",
  phone: "+91 98765 43210",
  address: "Near Charminar, Hyderabad",
  points: 450,
  tier: "Silver" as const,
  streak: 25,
  creditLimit: 5000,
  creditUsed: 2100,
};

export const translations = {
  en: {
    greeting: "Namaste",
    dashboard: "Home",
    catalog: "Catalog",
    orders: "Orders",
    loyalty: "Rewards",
    profile: "Profile",
    cart: "Cart",
    streak: "Streak",
    points: "Points",
    addToCart: "Add to Cart",
    placeOrder: "Place Order",
    reorder: "Reorder",
    todayOrders: "Today's Orders",
    viewAll: "View All",
    searchProducts: "Search products...",
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    creditWallet: "Credit wallet",
    used: "Used",
    settings: "Settings",
    language: "Language",
    notificationSettings: "Notification settings",
    viewNotifications: "View notifications",
    community: "Community",
    vendorForum: "Vendor forum",
    upskillCourses: "Upskill courses",
    logout: "Logout",
    editProfile: "Edit profile",
    manageAccount: "Manage your account and preferences",
    insuranceOptIn: "Insurance: Opt-in available for your stall",
    tier: "Tier",
    default: "Default",
    sortPriceAsc: "Price: Low to high",
    sortPriceDesc: "Price: High to low",
    sortName: "Name A–Z",
    all: "All",
    essentials: "Essentials",
    disposables: "Disposables",
    kits: "Kits",
    eco: "Eco",
    noOrders: "No orders yet",
    profileUpdated: "Profile updated",
    saved: "Settings saved",
    addedToCart: "added to cart",
    orderPlaced: "Order placed successfully!",
    orderPlacedDraw: "Order placed! You're entered in today's draw",
    markAllRead: "Mark all read",
    noNotifications: "No notifications",
    adminDashboard: "Admin dashboard",
    admin: "Admin",
    gst: "GST",
    allSectors: "All Sectors",
    inStock: "In Stock",
    outOfStock: "Out of stock",
    subtotal: "Subtotal",
    gstAmount: "GST",
    total: "Total",
    discount: "Discount",
    sales: "Sales",
    mySalesMenu: "My Shop Menu",
    activateDefault: "Activate Default Menu",
    defaultPrice: "Default price",
    yourPrice: "Your price",
    save: "Save",
    pos: "POS",
    cashPaid: "Cash Paid",
    generateUpiQr: "Generate UPI QR",
    newOnlineOrder: "New online order!",
    salesOverview: "Sales Overview",
    dailyRevenue: "Today's revenue",
    topItems: "Top items",
    grossProfit: "Gross profit",
    savingsThisWeek: "Savings this week",
    qrCodeMenu: "QR Code Menu",
    onlineMenu: "Online menu",
    payOnline: "Pay online",
    heroHeadline: "Power Your Street Business – Buy Supplies & Sell Smarter",
    heroSubtitle: "Get wholesale essentials with credit & rewards. Manage your menu, POS, and customer orders easily.",
    tileBuyHeadline: "Buy Supplies & Save",
    tileBuyCta: "Go to Purchases",
    tileBuyCtaLoggedIn: "Continue to Purchases",
    tileBuyFooter: "For stocking your stall",
    tileSellHeadline: "Sell to Customers & Grow",
    tileSellCta: "Go to My Shop",
    tileSellCtaLoggedIn: "Continue to Sales",
    tileSellFooter: "Manage your daily sales",
    signIn: "Sign in",
    signUp: "Sign up",
    signInSignUp: "Sign in / Sign up",
    myShop: "My Shop",
    dailyIncentives: "Daily Incentives",
    referralBonus: "Referral Bonus",
    inviteVendors: "Invite Vendors",
    referralBonusDesc: "Share your link. Earn ₹100 when a referred vendor hits 100 entries.",
    copyLink: "Copy link",
    withdraw: "Withdraw",
  },
  hi: {
    greeting: "नमस्ते",
    dashboard: "होम",
    catalog: "कैटलॉग",
    orders: "ऑर्डर",
    loyalty: "रिवार्ड्स",
    profile: "प्रोफ़ाइल",
    cart: "कार्ट",
    streak: "स्ट्रीक",
    points: "पॉइंट्स",
    addToCart: "कार्ट में डालें",
    placeOrder: "ऑर्डर दें",
    reorder: "फिर से ऑर्डर",
    todayOrders: "आज के ऑर्डर",
    viewAll: "सभी देखें",
    searchProducts: "प्रोडक्ट खोजें...",
    goodMorning: "सुप्रभात",
    goodAfternoon: "शुभ दोपहर",
    goodEvening: "शुभ संध्या",
    creditWallet: "क्रेडिट वॉलेट",
    used: "इस्तेमाल",
    settings: "सेटिंग्स",
    language: "भाषा",
    notificationSettings: "नोटिफिकेशन सेटिंग्स",
    viewNotifications: "नोटिफिकेशन देखें",
    community: "कम्युनिटी",
    vendorForum: "वेंडर फोरम",
    upskillCourses: "अपस्किल कोर्स",
    logout: "लॉगआउट",
    editProfile: "प्रोफाइल संपादित करें",
    manageAccount: "अपना खाता और प्राथमिकताएं प्रबंधित करें",
    insuranceOptIn: "बीमा: आपके स्टॉल के लिए ऑप्ट-इन उपलब्ध",
    tier: "टियर",
    default: "डिफॉल्ट",
    sortPriceAsc: "कीमत: कम से ज्यादा",
    sortPriceDesc: "कीमत: ज्यादा से कम",
    sortName: "नाम A–Z",
    all: "सभी",
    essentials: "जरूरी",
    disposables: "डिस्पोजेबल",
    kits: "किट",
    eco: "इको",
    noOrders: "अभी कोई ऑर्डर नहीं",
    profileUpdated: "प्रोफाइल अपडेट हो गई",
    saved: "सेटिंग्स सेव हो गईं",
    addedToCart: "कार्ट में डाल दिया",
    orderPlaced: "ऑर्डर सफलतापूर्वक दिया गया!",
    orderPlacedDraw: "ऑर्डर दिया! आज के ड्रॉ में आप शामिल हैं",
    markAllRead: "सभी पढ़े हुए मार्क करें",
    noNotifications: "कोई नोटिफिकेशन नहीं",
    adminDashboard: "एडमिन डैशबोर्ड",
    admin: "एडमिन",
    gst: "जीएसटी",
    allSectors: "सभी सेक्टर",
    inStock: "स्टॉक में",
    outOfStock: "स्टॉक खत्म",
    subtotal: "उप-योग",
    gstAmount: "जीएसटी",
    total: "कुल",
    discount: "छूट",
    sales: "सेल्स",
    mySalesMenu: "मेरा शॉप मेन्यू",
    activateDefault: "डिफॉल्ट मेन्यू एक्टिवेट करें",
    defaultPrice: "डिफॉल्ट कीमत",
    yourPrice: "आपकी कीमत",
    save: "सेव",
    pos: "POS",
    cashPaid: "कैश पेड",
    generateUpiQr: "UPI QR बनाएं",
    newOnlineOrder: "नया ऑनलाइन ऑर्डर!",
    salesOverview: "सेल्स ओवरव्यू",
    dailyRevenue: "आज की कमाई",
    topItems: "टॉप आइटम",
    grossProfit: "ग्रॉस प्रॉफिट",
    savingsThisWeek: "इस हफ्ते की बचत",
    qrCodeMenu: "QR कोड मेन्यू",
    onlineMenu: "ऑनलाइन मेन्यू",
    payOnline: "ऑनलाइन पे करें",
    heroHeadline: "अपना स्ट्रीट बिजनेस चलाएं – सप्लाई खरीदें और स्मार्ट बेचें",
    heroSubtitle: "क्रेडिट और रिवॉर्ड्स के साथ होलसेल जरूरतें पाएं। मेन्यू, POS और कस्टमर ऑर्डर आसानी से मैनेज करें।",
    tileBuyHeadline: "सप्लाई खरीदें और बचाएं",
    tileBuyCta: "खरीदारी पर जाएं",
    tileBuyCtaLoggedIn: "खरीदारी जारी रखें",
    tileBuyFooter: "अपने स्टॉल के लिए स्टॉक",
    tileSellHeadline: "ग्राहकों को बेचें और ग्रो करें",
    tileSellCta: "मेरी शॉप पर जाएं",
    tileSellCtaLoggedIn: "सेल्स जारी रखें",
    tileSellFooter: "रोज़ की बिक्री मैनेज करें",
    signIn: "साइन इन",
    myShop: "मेरी शॉप",
    dailyIncentives: "दैनिक इनकेंटिव",
    referralBonus: "रेफरल बोनस",
    inviteVendors: "वेंडर को आमंत्रित करें",
    referralBonusDesc: "अपना लिंक शेयर करें। रेफर किए गए वेंडर के 100 एंट्री हिट करने पर ₹100 कमाएं।",
    copyLink: "लिंक कॉपी करें",
    withdraw: "वितरण",
  },
  te: {
    greeting: "నమస్తే",
    dashboard: "హోమ్",
    catalog: "కేటలాగ్",
    orders: "ఆర్డర్లు",
    loyalty: "రివార్డ్స్",
    profile: "ప్రొఫైల్",
    cart: "కార్ట్",
    streak: "స్ట్రీక్",
    points: "పాయింట్లు",
    addToCart: "కార్ట్‌లో జోడించు",
    placeOrder: "ఆర్డర్ చేయండి",
    reorder: "మళ్ళీ ఆర్డర్",
    todayOrders: "నేటి ఆర్డర్లు",
    viewAll: "అన్నీ చూడండి",
    searchProducts: "ఉత్పత్తులు వెతకండి...",
    goodMorning: "శుభోదయం",
    goodAfternoon: "శుభ మద్యాహ్నం",
    goodEvening: "శుభ సాయంత్రం",
    creditWallet: "క్రెడిట్ వాలెట్",
    used: "ఉపయోగం",
    settings: "సెట్టింగ్‌లు",
    language: "భాష",
    notificationSettings: "నోటిఫికేషన్ సెట్టింగ్‌లు",
    viewNotifications: "నోటిఫికేషన్లు చూడండి",
    community: "కమ్యూనిటీ",
    vendorForum: "వెండర్ ఫోరం",
    upskillCourses: "అప్‌స్కిల్ కోర్సులు",
    logout: "లాగౌట్",
    editProfile: "ప్రొఫైల్ సవరించండి",
    manageAccount: "మీ ఖాతా మరియు ప్రాధాన్యతలను నిర్వహించండి",
    insuranceOptIn: "ఇన్సురెన్స్: మీ స్టాల్‌కు ఆప్ట్-ఇన్ అందుబాటులో ఉంది",
    tier: "టైర్",
    default: "డిఫాల్ట్",
    sortPriceAsc: "ధర: తక్కువ నుండి ఎక్కువ",
    sortPriceDesc: "ధర: ఎక్కువ నుండి తక్కువ",
    sortName: "పేరు A–Z",
    all: "అన్నీ",
    essentials: "అవసరమైనవి",
    disposables: "డిస్పోజబుల్స్",
    kits: "కిట్లు",
    eco: "ఎకో",
    noOrders: "ఇంకా ఆర్డర్లు లేవు",
    profileUpdated: "ప్రొఫైల్ నవీకరించబడింది",
    saved: "సెట్టింగ్‌లు సేవ్ అయ్యాయి",
    addedToCart: "కార్ట్‌లో జోడించబడింది",
    orderPlaced: "ఆర్డర్ విజయవంతంగా ఇవ్వబడింది!",
    orderPlacedDraw: "ఆర్డర్ ఇవ్వబడింది! నేటి డ్రాలో మీరు ఎంటర్ అయ్యారు",
    markAllRead: "అన్నీ చదివినట్లు గుర్తించండి",
    noNotifications: "నోటిఫికేషన్లు లేవు",
    adminDashboard: "అడ్మిన్ డాష్‌బోర్డ్",
    admin: "అడ్మిన్",
    gst: "జీఎస్‌టీ",
    allSectors: "అన్ని సెక్టార్లు",
    inStock: "స్టాక్‌లో ఉంది",
    outOfStock: "స్టాక్ అయిపోయింది",
    subtotal: "ఉపమొత్తం",
    gstAmount: "జీఎస్‌టీ",
    total: "మొత్తం",
    discount: "తగ్గింపు",
    sales: "విక్రయాలు",
    mySalesMenu: "నా షాప్ మెనూ",
    activateDefault: "డిఫాల్ట్ మెనూ యాక్టివేట్ చేయండి",
    defaultPrice: "డిఫాల్ట్ ధర",
    yourPrice: "మీ ధర",
    save: "సేవ్",
    pos: "POS",
    cashPaid: "నగదు చెల్లించారు",
    generateUpiQr: "UPI QR జనరేట్ చేయండి",
    newOnlineOrder: "కొత్త ఆన్‌లైన్ ఆర్డర్!",
    salesOverview: "విక్రయాల అవలోకనం",
    dailyRevenue: "ఈ రోజు రెవెన్యూ",
    topItems: "టాప్ ఐటమ్లు",
    grossProfit: "స్థూల లాభం",
    savingsThisWeek: "ఈ వారం పొదుపు",
    qrCodeMenu: "QR కోడ్ మెనూ",
    onlineMenu: "ఆన్‌లైన్ మెనూ",
    payOnline: "ఆన్‌లైన్ చెల్లించండి",
    heroHeadline: "మీ వీధి వ్యాపారాన్ని శక్తివంతం చేయండి – సరఫరా కొనండి మరియు తెలివిగా అమ్మండి",
    heroSubtitle: "క్రెడిట్ మరియు రివార్డ్‌లతో హోల్‌సేల్ ఎసెన్షియల్స్ పొందండి. మీ మెనూ, POS మరియు కస్టమర్ ఆర్డర్లను సులభంగా నిర్వహించండి.",
    tileBuyHeadline: "సరఫరా కొనండి మరియు ఆదా చేయండి",
    tileBuyCta: "కొనుగోళ్లకు వెళ్లండి",
    tileBuyCtaLoggedIn: "కొనుగోళ్లను కొనసాగించండి",
    tileBuyFooter: "మీ స్టాల్‌కు స్టాక్ చేయడానికి",
    tileSellHeadline: "కస్టమర్లకు అమ్మండి మరియు వృద్ధి చేయండి",
    tileSellCta: "నా షాప్‌కు వెళ్లండి",
    tileSellCtaLoggedIn: "విక్రయాలను కొనసాగించండి",
    tileSellFooter: "మీ రోజువారీ విక్రయాలను నిర్వహించండి",
    signIn: "సైన్ ఇన్",
    signUp: "సైన్ అప్",
    signInSignUp: "సైన్ ఇన్ / సైన్ అప్",
    myShop: "నా షాప్",
    dailyIncentives: "రోజువారీ ప్రోత్సాహకాలు",
    referralBonus: "రిఫరల్ బోనస్",
    inviteVendors: "వెండర్లను ఆహ్వానించండి",
    referralBonusDesc: "మీ లింక్ షేర్ చేయండి. రిఫర్ చేసిన వెండర్ 100 ఎంట్రీలు చేరినప్పుడు ₹100 సంపాదించండి.",
    copyLink: "లింక్ కాపీ చేయండి",
    withdraw: "విత్‌డ్రా",
  },
};

export type Language = keyof typeof translations;

export function getProductDescription(p: Product, lang: Language): string {
  if (lang === "hi") return p.descriptionHi;
  if (lang === "te") return p.descriptionTe;
  return p.description;
}
