export interface Product {
  id: string;
  name: string;
  nameHi: string;
  nameTe: string;
  price: number;
  image: string;
  category: string;
  eco: boolean;
  description: string;
  descriptionHi: string;
  descriptionTe: string;
}

export interface Order {
  id: string;
  items: { product: Product; qty: number }[];
  total: number;
  date: string;
  status: "pending" | "delivered" | "in-transit";
}

export interface CartItem {
  product: Product;
  qty: number;
  /** Catalog variant (for GST invoice) */
  variantId?: string;
  variantLabel?: string;
  /** Price in paise when from catalog; else derived from product.price * 100 */
  pricePaise?: number;
  gstRate?: number;
  mrpPaise?: number;
}

export const products: Product[] = [
  { id: "1", name: "Paper Plates (100 pcs)", nameHi: "पेपर प्लेट (100)", nameTe: "పేపర్ ప్లేట్లు (100)", price: 99, image: "🍽️", category: "Disposables", eco: true, description: "Biodegradable paper plates, perfect for street food serving.", descriptionHi: "बायोडिग्रेडेबल पेपर प्लेट, स्ट्रीट फूड सर्विंग के लिए बढ़िया।", descriptionTe: "బయోడిగ్రేడబుల్ పేపర్ ప్లేట్లు, వీధి ఫుడ్ సర్వింగ్‌కు అనువైనవి." },
  { id: "2", name: "Matchbox Pack (10)", nameHi: "माचिस पैक (10)", nameTe: "అగ్గిపెట్టె ప్యాక్ (10)", price: 30, image: "🔥", category: "Essentials", eco: false, description: "Standard safety matches, 10 boxes per pack.", descriptionHi: "स्टैंडर्ड सेफ्टी माचिस, 10 बॉक्स प्रति पैक।", descriptionTe: "స్టాండర్డ్ సేఫ్టీ అగ్గిపెట్టెలు, ప్యాక్‌కు 10 బాక్స్లు." },
  { id: "3", name: "Water Bottles Case (24)", nameHi: "पानी बोतल केस (24)", nameTe: "నీటి బాటిళ్ల కేస్ (24)", price: 240, image: "💧", category: "Essentials", eco: false, description: "500ml drinking water bottles, 24 per case.", descriptionHi: "500ml पीने का पानी बोतलें, 24 प्रति केस।", descriptionTe: "500ml తాగే నీటి బాటిళ్లు, కేస్‌కు 24." },
  { id: "4", name: "Paper Cups (200 pcs)", nameHi: "पेपर कप (200)", nameTe: "పేపర్ కప్పులు (200)", price: 150, image: "☕", category: "Disposables", eco: true, description: "Eco-friendly paper cups for hot beverages.", descriptionHi: "गर्म पेय के लिए इको-फ्रेंडली पेपर कप।", descriptionTe: "వేడి పానీయాలకు పర్యావరణ స్నేహపరమైన పేపర్ కప్పులు." },
  { id: "5", name: "Plastic Spoons (100)", nameHi: "प्लास्टिक चम्मच (100)", nameTe: "ప్లాస్టిక్ స్పూన్లు (100)", price: 60, image: "🥄", category: "Disposables", eco: false, description: "Sturdy disposable spoons, 100 per pack.", descriptionHi: "मजबूत डिस्पोजेबल चम्मच, 100 प्रति पैक।", descriptionTe: "గట్టి డిస్పోజబుల్ స్పూన్లు, ప్యాక్‌కు 100." },
  { id: "6", name: "Napkins Bundle (500)", nameHi: "नैपकिन बंडल (500)", nameTe: "నాప్కిన్ల బండిల్ (500)", price: 120, image: "🧻", category: "Essentials", eco: true, description: "Soft tissue napkins, bulk pack of 500.", descriptionHi: "सॉफ्ट टिश्यू नैपकिन, 500 का बल्क पैक।", descriptionTe: "సాఫ్ట్ టిష్యూ నాప్కిన్లు, 500 బల్క్ ప్యాక్." },
  { id: "7", name: "Tea Powder (1kg)", nameHi: "चाय पाउडर (1kg)", nameTe: "టీ పొడి (1kg)", price: 320, image: "🍵", category: "Essentials", eco: false, description: "Premium CTC tea powder, 1kg pack.", descriptionHi: "प्रीमियम CTC चाय पाउडर, 1kg पैक।", descriptionTe: "ప్రీమియం CTC టీ పొడి, 1kg ప్యాక్." },
  { id: "8", name: "Sugar (5kg)", nameHi: "चीनी (5kg)", nameTe: "చక్కెర (5kg)", price: 250, image: "🍬", category: "Essentials", eco: false, description: "Refined sugar, 5kg bag.", descriptionHi: "रिफाइंड चीनी, 5kg बैग।", descriptionTe: "రిఫైన్డ్ చక్కెర, 5kg బ్యాగ్." },
  { id: "9", name: "Panipuri Kit", nameHi: "पानीपुरी किट", nameTe: "పానీపూరీ కిట్", price: 500, image: "🎪", category: "Kits", eco: false, description: "Complete panipuri starter kit: plates + cups + napkins + water.", descriptionHi: "कंप्लीट पानीपुरी स्टार्टर किट: प्लेट + कप + नैपकिन + पानी।", descriptionTe: "పూర్తి పానీపూరీ స్టార్టర్ కిట్: ప్లేట్లు + కప్పులు + నాప్కిన్లు + నీరు." },
  { id: "10", name: "Eco Serve Bundle", nameHi: "इको सर्व बंडल", nameTe: "ఎకో సర్వ్ బండిల్", price: 399, image: "🌿", category: "Kits", eco: true, description: "All eco-friendly: biodegradable plates, cups, and napkins.", descriptionHi: "ऑल इको-फ्रेंडली: बायोडिग्रेडेबल प्लेट, कप और नैपकिन।", descriptionTe: "అన్నీ పర్యావరణ స్నేహపరం: బయోడిగ్రేడబుల్ ప్లేట్లు, కప్పులు మరియు నాప్కిన్లు." },
];

export const sampleOrders: Order[] = [
  { id: "ORD-1001", items: [{ product: products[0], qty: 3 }, { product: products[3], qty: 2 }], total: 597, date: "2026-02-15", status: "delivered" },
  { id: "ORD-1002", items: [{ product: products[8], qty: 2 }, { product: products[2], qty: 1 }], total: 1240, date: "2026-02-14", status: "in-transit" },
  { id: "ORD-1003", items: [{ product: products[6], qty: 1 }], total: 320, date: "2026-02-13", status: "delivered" },
  { id: "ORD-1004", items: [{ product: products[1], qty: 5 }, { product: products[5], qty: 2 }], total: 390, date: "2026-02-12", status: "delivered" },
];

export const vendorProfile = {
  name: "Vendor",
  stallType: "Kirana/General Store",
  stallIcon: "☕",
  phone: "+91 7330333743",
  address: "Flat 505, Balaji Homes, Opposite Shivams Banquet Halls, Near New Bus Stand, Siddipet, Telangana - 502103",
  points: 450,
  tier: "Silver" as const,
  streak: 25,
  creditLimit: 5000,
  creditUsed: 2100,
};

export const translations = {
  en: {
    greeting: "Namaste",
    dashboard: "Home",
    catalog: "Products",
    catalogPageSubtitle: "Buy supplies to stock your dukaan",
    browseProducts: "Browse products",
    viewFullProducts: "View full products",
    browseProductsToOrder: "Browse products to order supplies",
    orders: "Buying Spot",
    ordersPageSubtitle: "Orders you placed for supplies",
    loyalty: "Rewards",
    profile: "Profile",
    cart: "Cart",
    streak: "Streak",
    points: "Points",
    addToCart: "Add to Cart",
    placeOrder: "Place Order",
    reorder: "Reorder",
    todayOrders: "Today's Orders",
    viewAll: "View All",
    searchProducts: "Search products...",
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    creditWallet: "Credit wallet",
    used: "Used",
    settings: "Settings",
    language: "Language",
    notificationSettings: "Notification settings",
    viewNotifications: "View notifications",
    community: "Community",
    vendorForum: "Dukaanwaale forum",
    vendorSwap: "Dukaan Swap",
    upskillCourses: "Upskill courses",
    logout: "Logout",
    editProfile: "Edit profile",
    manageAccount: "Manage your account and preferences",
    insuranceOptIn: "Insurance: Opt-in available for your dukaan",
    tier: "Tier",
    default: "Default",
    sortPriceAsc: "Price: Low to high",
    sortPriceDesc: "Price: High to low",
    sortName: "Name A–Z",
    all: "All",
    essentials: "Essentials",
    disposables: "Disposables",
    electricals: "Electricals",
    chipKirana: "Kirana",
    chipGeneral: "General",
    chipTeaStall: "Tea Stall",
    chipPaniPuri: "Pani Puri",
    chipHardware: "Hardware",
    chipSaloon: "Saloon",
    kits: "Kits",
    eco: "Eco",
    noOrders: "No orders yet",
    profileUpdated: "Profile updated",
    saved: "Settings saved",
    addedToCart: "added to cart",
    orderPlaced: "Order placed successfully!",
    orderPlacedDraw: "Order placed! You're entered in today's draw",
    markAllRead: "Mark all read",
    noNotifications: "No notifications",
    adminDashboard: "Admin dashboard",
    admin: "Admin",
    gst: "GST",
    allSectors: "All Sectors",
    inStock: "In Stock",
    outOfStock: "Out of stock",
    subtotal: "Subtotal",
    gstAmount: "GST",
    total: "Total",
    discount: "Discount",
    sales: "My Shop",
    mySalesMenu: "My Shop – Menu & Sales",
    activateDefault: "Activate Default Menu for Your Dukaan Type",
    defaultPrice: "Default price",
    yourPrice: "Your price",
    save: "Save",
    pos: "POS",
    cashPaid: "Cash Paid",
    generateUpiQr: "Generate UPI QR",
    newOnlineOrder: "New online order!",
    salesPageSubtitle: "Sell to customers – menu, POS, online orders",
    salesOverview: "Sales Overview",
    dailyRevenue: "Today's revenue",
    topItems: "Top items",
    grossProfit: "Gross profit",
    savingsThisWeek: "Savings this week",
    qrCodeMenu: "QR Code Menu",
    onlineMenu: "Online menu",
    payOnline: "Pay online",
    payOnlineNow: "Pay online now",
    payAtDukaanWhenCollect: "Pay at dukaan when I collect",
    tagline: "Sab Kuch Haath Pe",
    heroHeadline: "haathpe – Har Chhoti Dukaan Ka Dost",
    heroSubtitle: "Kirana se tea stall tak – supplies, sales, paise… sab haath pe",
    tileBuyBadge: "Buy supplies",
    tileSellBadge: "Sell to customers",
    tileBuyHeadline: "Stock Up for Your Dukaan",
    tileBuyCta: "Buy supplies for my shop",
    tileBuyCtaLoggedIn: "Go to Buy Supplies",
    tileBuyFooter: "Buy plates, chai, kirana items – stock your dukaan",
    tileSellHeadline: "Run Your Shop & Sell",
    tileSellCta: "Open my shop (sell to customers)",
    tileSellCtaLoggedIn: "Go to My Shop",
    tileSellFooter: "Sell to customers – menu, POS, online orders",
    signIn: "Sign in",
    signUp: "Sign up",
    signInSignUp: "Sign in / Sign up",
    myShop: "My Shop",
    dailyIncentives: "Daily Incentives",
    referralBonus: "Referral Bonus",
    inviteVendors: "Invite Dukaanwaale",
    referralBonusDesc: "Share your link. Earn ₹100 when a referred dukaanwaala hits 100 entries.",
    copyLink: "Copy link",
    withdraw: "Withdraw",
    customerLoginTitle: "Login with phone",
    customerLoginSubtitle: "Save favorites & track orders",
    customerLoginPhone: "Mobile number",
    customerLoginSendOtp: "Send OTP",
    customerLoginOtpSent: "OTP sent! Check your phone.",
    customerLoginOtpSentTo: "Code sent to",
    customerLoginOtpCode: "Enter 6-digit code",
    customerLoginVerify: "Verify",
    customerLoginVerifying: "Verifying…",
    customerLoginChangeNumber: "Change number",
    customerLoginContinueGuest: "Continue as Guest",
    customerLoginInvalidPhone: "Enter a valid 10-digit number",
    customerLoginError: "Something went wrong. Try again.",
    customerLoginSuccess: "Welcome back!",
    customerLoginBanner: "Login with phone to save favorites & track orders",
    mpinCreateTitle: "Create your 4-digit MPIN",
    mpinCreateSubtitle: "Use MPIN next time to sign in (saves OTP cost)",
    mpinPlaceholder: "Enter 4-digit MPIN",
    mpinConfirmPlaceholder: "Confirm MPIN",
    mpinMismatch: "MPINs don't match",
    mpinSetSuccess: "MPIN set! Use it next time to sign in.",
    mpinSetting: "Setting…",
    mpinSignInTitle: "Sign in with MPIN",
    mpinSignInSubtitle: "Phone + MPIN (no OTP needed)",
    mpinEnter: "Enter MPIN",
    mpinInvalid: "Wrong phone or MPIN",
    mpinSignIn: "Sign in with MPIN",
    addToFavorites: "Add to favorites",
    removeFromFavorites: "Remove from favorites",
    orderSavedToHistory: "Order saved to your history",
    welcomeBack: "Welcome back!",
    customerOrders: "My orders",
    customerOrdersTitle: "Your orders",
    customerOrdersEmpty: "No orders yet",
    customerLogout: "Log out",
    customerWallet: "Wallet",
    walletBalance: "Wallet Balance",
    redeemNow: "Redeem Now",
    recentTransactions: "Recent transactions",
    noTransactions: "No transactions yet",
    earnCoinsOnOrder: "Earn coins on every order!",
    customerTransactions: "Transactions",
    credit: "Credit",
    debit: "Debit",
    redemptionRequested: "Redemption requested!",
    redemptionPendingNote: "Admin will process your request shortly.",
    backToWallet: "Back to Wallet",
    selectRedemptionType: "Select redemption type",
    amountToRedeem: "Amount to redeem",
    availableBalance: "Available",
    minCash100: "Min ₹100 for cash",
    minRedeem10: "Min ₹10",
    submitRedemption: "Submit",
    back: "Back",
    coinsEarned: "Coins earned",
    congratulationsCoins: "Congratulations! You earned {n} coins – added to your wallet!",
    useWallet: "Use Wallet",
    walletAvailable: "₹{amount} available",
    searchTitle: "Find dukaan near you",
    searchPlaceholder: "Search by dukaan name, type or item (e.g. PaniPuri, chai, kirana)",
    searchZoneAll: "All zones",
    searchZoneGeneral: "Hyderabad",
    searchStallTypeAll: "All types",
    searchStallTypeKirana: "Kirana Store",
    searchStallTypeGeneral: "General Store",
    searchStallTypePanipuri: "Pani Puri",
    searchStallTypeChai: "Chai / Tea",
    searchStallTypeTiffin: "Tiffin",
    searchStallTypePan: "Pan",
    searchStallTypeFastFood: "Fast Food",
    searchStallTypeSnacks: "Snacks",
    searchStallTypeBeverage: "Beverages",
    searchStallTypeFood: "Food",
    searchStallTypeHardware: "Hardware Shop",
    searchStallTypeSaloon: "Saloon / Spa",
    sortPopular: "Most popular",
    viewMenu: "View Menu",
    searchVendorUnknown: "Dukaanwaala",
    searchOrdersLabel: "orders",
    searchEmptyTitle: "No dukaanwaale found",
    searchEmptySubtitle: "Ask your local dukaan to join haathpe!",
    searchFindVendors: "Find dukaan near you",
    customerSignIn: "Customer sign in",
    browseSuppliesForDukaan: "Buy supplies for your dukaan",
    reviewModalTitle: "Rate & Review",
    reviewModalPlaceholder: "Share your experience (optional)",
    reviewModalCancel: "Cancel",
    reviewModalSubmit: "Submit review",
    reviewModalSubmitting: "Submitting...",
    reviewStars: "stars",
    rateAndReview: "Rate & Review",
    statusPending: "Order placed",
    statusPrepared: "Preparing",
    statusReady: "Ready for pickup",
    statusDelivered: "Delivered",
    trackOrder: "Track order",
    orderId: "Order ID",
    shareTracking: "Share tracking",
    deliveryPickup: "Pickup",
    deliverySelf: "Self Delivery",
    deliveryAddressPlaceholder: "Enter delivery address",
    vendorWillDeliver: "Dukaanwaala will deliver (contact for time)",
    customerReviews: "Customer Reviews",
    averageRating: "Average rating",
    noReviewsYet: "No reviews yet",
    sortRating: "Top rated",
    searchUpsellSupplies: "Need plates/cups? Buy supplies →",
    premiumUpgrade: "Upgrade to Premium",
    premiumPrice: "₹99/month",
    premiumBenefits: "Boosted search, priority listing, custom themes",
    premiumUpgradeCta: "Upgrade",
    zeroFeeMessage: "No commissions on discovery — only 3% on ONDC orders (PhonePe, Paytm, etc.)",
    gstNote: "GST extra as applicable",
    ondcExport: "Catalog export",
    ondcOrders: "Online Orders",
    ondcFeeNote: "Platform fee applies to online orders as set by admin.",
    noOndcOrders: "No online orders yet",
    onlineOrders: "Online Orders",
    catalogExport: "Catalog export",
    catalogExportTitle: "Export your menu",
    catalogExportDesc: "Download your menu as a JSON file. Use it to sync your catalog for online orders.",
    catalogExportFutureTitle: "Coming soon",
    catalogExportFutureDesc: "Live catalog sync and automatic updates will be available soon.",
    onlineOrderFeeNote: "Platform fee applies to online orders as set by admin.",
    noOnlineOrders: "No online orders yet",
    newOnlineOrderToast: "New online order received: ₹{amount}",
    orderSourceOnline: "Online",
    yourShare: "Your share",
    paid: "Paid",
    ondcEnabled: "Online orders enabled",
    ondcMenuLive: "Your menu is live for online orders!",
    upiPayoutHint: "For instant online order payouts (e.g. merchant@upi)",
    upiForPayout: "UPI for instant payout",
    upiPlaceholder: "merchant@upi",
    dukaanType: "Dukaan Type",
    stallType: "Stall Type",
    dukaanAddress: "Dukaan Address",
    shopTimingsTitle: "Dukaan Timings & Online Status",
    shopTimingsDesc: "Set hours, weekly off, holidays. Toggle online orders.",
    editTimings: "Edit timings",
    onlineOrdersAvailable: "Online Orders Available",
    openTime: "Open time",
    closeTime: "Close time",
    weeklyOff: "Weekly off",
    shopHolidays: "Holidays (YYYY-MM-DD, one per line)",
    shopOpenNow: "Aapka dukaan abhi OPEN hai",
    shopClosedNow: "Aapka dukaan abhi band hai",
    dukaanClosedTitle: "Dukaan abhi band hai",
    currentlyUnavailable: "Currently unavailable",
    dashboardGreeting: "Aapka dukaan haath pe hai",
    footerTagline: "haathpe – Sab Kuch Haath Pe | No commissions on discovery",
    landingFeaturesNav: "Features",
    landingHowItWorksNav: "How it works",
    landingDukaanwaaleNav: "Dukaanwaale",
    signedInAs: "Signed in as",
    logOut: "Log out",
    landingHeroPin: "Kirana, tea stall, hardware & more — Hyderabad",
    landingHeroTagline: "Your dukaan, simplified",
    landingForEveryDukaan: "For every chhoti dukaan — kirana to saloon",
    landingWhyLoveUs: "Why dukaanwaale love us",
    landingWhyLoveUsDesc: "Built for the daily grind. Order supplies, build credit, and earn rewards — all from your phone.",
    featureEasySupplies: "Easy Supplies",
    featureEasySuppliesDesc: "Paper plates, cups, matchboxes — delivered to your dukaan in hours across Hyderabad.",
    featureUnlockCredit: "Unlock Credit",
    featureUnlockCreditDesc: "Order 20/30 days straight and unlock credit lines so you never run out of stock.",
    featureEarnRedeem: "Earn & Redeem",
    featureEarnRedeemDesc: "Earn loyalty points on every order. Redeem for family trips, cash prizes & supplies.",
    buyBullet1: "Wholesale matchboxes, plates, rice, etc.",
    buyBullet2: "Unlock credit on streaks",
    buyBullet3: "Earn loyalty points & trips",
    buyBullet4: "Fast Hyderabad delivery",
    sellBullet1: "Ready default menu for your dukaan type",
    sellBullet2: "Quick POS at dukaan (cash/UPI)",
    sellBullet3: "Online orders via QR code",
    sellBullet4: "Track sales, profits & re-order suggestions",
    landingHowItWorksTitle: "How it works",
    landingHowItWorksSub: "Four steps to supplies, credit, and rewards.",
    step1Title: "Sign up",
    step1Body: "Create your dukaan account with phone or email in under a minute.",
    step2Title: "Order supplies",
    step2Body: "Browse products, add to cart, and place orders. Same-day delivery in Hyderabad.",
    step3Title: "Build streak & credit",
    step3Body: "Order regularly to build your streak and unlock credit lines for your dukaan.",
    step4Title: "Earn rewards",
    step4Body: "Collect points, enter daily draws, and redeem for vouchers and prizes.",
    faqCommonQuestions: "Common questions",
    faqWhoCanJoin: "Who can join haathpe?",
    faqWhoCanJoinA: "Any small retailer or dukaanwaala in our service area (Hyderabad and expanding) can join. You need a phone number to sign up. No GST or paperwork required to start ordering supplies.",
    faqHowFastDelivery: "How fast is delivery?",
    faqHowFastDeliveryA: "We offer same-day delivery across Hyderabad for orders placed in the morning. You can track your order in the app. Delivery slots depend on your area — most dukaanwaale get supplies within a few hours.",
    faqRedeemPoints: "What can I redeem my points for?",
    faqRedeemPointsA: "Points can be redeemed for family trips, cash prizes, daily draws, and supplies. You also get better credit limits and rewards as you maintain your ordering streak.",
    landingDukaanwaaleLikeYou: "Dukaanwaale like you",
    landingDukaanwaaleDesc: "Real stories from Hyderabad's chai wallahs, snack sellers, and street food heroes.",
    testimonial1Name: "Raju",
    testimonial1Stall: "Tea dukaan near Charminar",
    testimonial1Quote: "Credit line helped me stock up before Ramadan. No more running to the wholesaler every day.",
    testimonial2Name: "Lakshmi",
    testimonial2Stall: "Snacks dukaan, Secunderabad",
    testimonial2Quote: "Points got my family a trip to Tirupati. This app is like a bonus for doing what I already do.",
    testimonial3Name: "Suresh",
    testimonial3Stall: "Beverage dukaan, Gachibowli",
    testimonial3Quote: "Delivery is fast. I order in the morning and get supplies by afternoon. Game changer.",
    statsDukaanwaale: "Dukaanwaale",
    statsOrdersDelivered: "Orders delivered",
    statsServingNow: "Serving now",
    landingWhatYouCanOrder: "What you can order",
    landingWhatYouCanOrderDesc: "Disposables, essentials, and ready-to-use kits for your dukaan.",
    productTeaser1: "🍽️ Paper plates & cups",
    productTeaser2: "🔥 Matchboxes & napkins",
    productTeaser3: "🍵 Tea, sugar & essentials",
    productTeaser4: "🎪 Panipuri & eco kits",
    landingReadyToGrow: "Ready to grow your dukaan?",
    landingJoinCta: "Join 1000+ dukaanwaale in Hyderabad. Get supplies delivered, build credit, and earn rewards.",
    landingStartNow: "Start now",
    landingDashboardNav: "Dashboard",
    platformFeeLabel: "Current Platform Fee",
    platformFeeExempt: "You are exempted from platform fee",
    platformFeeAdminNote: "Admin decides fee for online orders.",
    platformFeeUpdated: "Platform fee updated by admin",
  },
  hi: {
    greeting: "नमस्ते",
    dashboard: "होम",
    catalog: "उत्पाद",
    catalogPageSubtitle: "अपनी दुकान के लिए सप्लाई खरीदें",
    browseProducts: "उत्पाद देखें",
    viewFullProducts: "सभी उत्पाद देखें",
    browseProductsToOrder: "सप्लाई ऑर्डर करने के लिए उत्पाद देखें",
    orders: "खरीदने की जगह",
    ordersPageSubtitle: "आपके द्वारा दी गई सप्लाई ऑर्डर",
    loyalty: "रिवार्ड्स",
    profile: "प्रोफ़ाइल",
    cart: "कार्ट",
    streak: "स्ट्रीक",
    points: "पॉइंट्स",
    addToCart: "कार्ट में डालें",
    placeOrder: "ऑर्डर दें",
    reorder: "फिर से ऑर्डर",
    todayOrders: "आज के ऑर्डर",
    viewAll: "सभी देखें",
    searchProducts: "प्रोडक्ट खोजें...",
    goodMorning: "सुप्रभात",
    goodAfternoon: "शुभ दोपहर",
    goodEvening: "शुभ संध्या",
    creditWallet: "क्रेडिट वॉलेट",
    used: "इस्तेमाल",
    settings: "सेटिंग्स",
    language: "भाषा",
    notificationSettings: "नोटिफिकेशन सेटिंग्स",
    viewNotifications: "नोटिफिकेशन देखें",
    community: "कम्युनिटी",
    vendorForum: "दुकानदार फोरम",
    vendorSwap: "दुकान स्वैप",
    upskillCourses: "अपस्किल कोर्स",
    logout: "लॉगआउट",
    editProfile: "प्रोफाइल संपादित करें",
    manageAccount: "अपना खाता और प्राथमिकताएं प्रबंधित करें",
    insuranceOptIn: "बीमा: आपकी दुकान के लिए ऑप्ट-इन उपलब्ध",
    tier: "टियर",
    default: "डिफॉल्ट",
    sortPriceAsc: "कीमत: कम से ज्यादा",
    sortPriceDesc: "कीमत: ज्यादा से कम",
    sortName: "नाम A–Z",
    all: "सभी",
    essentials: "जरूरी",
    disposables: "डिस्पोजेबल",
    electricals: "इलेक्ट्रिकल",
    chipKirana: "किराना",
    chipGeneral: "जनरल",
    chipTeaStall: "चाय स्टॉल",
    chipPaniPuri: "पानी पुरी",
    chipHardware: "हार्डवेयर",
    chipSaloon: "सलून",
    kits: "किट",
    eco: "इको",
    noOrders: "अभी कोई ऑर्डर नहीं",
    profileUpdated: "प्रोफाइल अपडेट हो गई",
    saved: "सेटिंग्स सेव हो गईं",
    addedToCart: "कार्ट में डाल दिया",
    orderPlaced: "ऑर्डर सफलतापूर्वक दिया गया!",
    orderPlacedDraw: "ऑर्डर दिया! आज के ड्रॉ में आप शामिल हैं",
    markAllRead: "सभी पढ़े हुए मार्क करें",
    noNotifications: "कोई नोटिफिकेशन नहीं",
    adminDashboard: "एडमिन डैशबोर्ड",
    admin: "एडमिन",
    gst: "जीएसटी",
    allSectors: "सभी सेक्टर",
    inStock: "स्टॉक में",
    outOfStock: "स्टॉक खत्म",
    subtotal: "उप-योग",
    gstAmount: "जीएसटी",
    total: "कुल",
    discount: "छूट",
    sales: "मेरी दुकान",
    mySalesMenu: "मेरी दुकान – मेन्यू और बिक्री",
    activateDefault: "अपने दुकान प्रकार के लिए डिफॉल्ट मेन्यू एक्टिवेट करें",
    defaultPrice: "डिफॉल्ट कीमत",
    yourPrice: "आपकी कीमत",
    save: "सेव",
    pos: "POS",
    cashPaid: "कैश पेड",
    generateUpiQr: "UPI QR बनाएं",
    newOnlineOrder: "नया ऑनलाइन ऑर्डर!",
    salesPageSubtitle: "ग्राहकों को बेचें – मेन्यू, POS, ऑनलाइन ऑर्डर",
    salesOverview: "सेल्स ओवरव्यू",
    dailyRevenue: "आज की कमाई",
    topItems: "टॉप आइटम",
    grossProfit: "ग्रॉस प्रॉफिट",
    savingsThisWeek: "इस हफ्ते की बचत",
    qrCodeMenu: "QR कोड मेन्यू",
    onlineMenu: "ऑनलाइन मेन्यू",
    payOnline: "ऑनलाइन पे करें",
    payOnlineNow: "अभी ऑनलाइन पे करें",
    payAtDukaanWhenCollect: "लेना आते समय दुकान पर पे करूँगा",
    tagline: "सब कुछ हाथ पे",
    heroHeadline: "haathpe – हर छोटी दुकान का दोस्त",
    heroSubtitle: "किराना से चाय स्टॉल तक – सप्लाई, सेल्स, पैसे… सब हाथ पे",
    tileBuyBadge: "सप्लाई खरीदें",
    tileSellBadge: "ग्राहकों को बेचें",
    tileBuyHeadline: "अपनी दुकान के लिए स्टॉक करो",
    tileBuyCta: "मेरी दुकान के लिए सप्लाई खरीदें",
    tileBuyCtaLoggedIn: "सप्लाई खरीदने जाएं",
    tileBuyFooter: "प्लेट, चाय, किराना – अपनी दुकान का स्टॉक करें",
    tileSellHeadline: "दुकान चलाओ और बेचो",
    tileSellCta: "मेरी दुकान खोलें (ग्राहकों को बेचें)",
    tileSellCtaLoggedIn: "मेरी दुकान पर जाएं",
    tileSellFooter: "ग्राहकों को बेचें – मेन्यू, POS, ऑनलाइन ऑर्डर",
    signIn: "साइन इन",
    myShop: "मेरी दुकान",
    dailyIncentives: "दैनिक इनकेंटिव",
    referralBonus: "रेफरल बोनस",
    inviteVendors: "दुकानदारों को आमंत्रित करें",
    referralBonusDesc: "अपना लिंक शेयर करें। रेफर किए गए दुकानदार के 100 एंट्री हिट करने पर ₹100 कमाएं।",
    copyLink: "लिंक कॉपी करें",
    withdraw: "वितरण",
    customerLoginTitle: "फ़ोन से लॉगिन करें",
    customerLoginSubtitle: "फेवरिट्स सेव करें और ऑर्डर ट्रैक करें",
    customerLoginPhone: "मोबाइल नंबर",
    customerLoginSendOtp: "OTP भेजें",
    customerLoginOtpSent: "OTP भेज दिया! फोन चेक करें।",
    customerLoginOtpSentTo: "कोड भेजा गया",
    customerLoginOtpCode: "6 अंकों का कोड डालें",
    customerLoginVerify: "वेरिफाई करें",
    customerLoginVerifying: "वेरिफाई हो रहा है…",
    customerLoginChangeNumber: "नंबर बदलें",
    customerLoginContinueGuest: "गेस्ट के रूप में जारी रखें",
    customerLoginInvalidPhone: "सही 10 अंकों का नंबर डालें",
    customerLoginError: "कुछ गड़बड़ हुई। दोबारा कोशिश करें।",
    customerLoginSuccess: "वापसी पर स्वागत है!",
    customerLoginBanner: "फेवरिट्स सेव और ऑर्डर ट्रैक करने के लिए फोन से लॉगिन करें",
    mpinCreateTitle: "4 अंकों का MPIN बनाएं",
    mpinCreateSubtitle: "अगली बार साइन इन करने के लिए MPIN इस्तेमाल करें (OTP बचत)",
    mpinPlaceholder: "4 अंकों का MPIN डालें",
    mpinConfirmPlaceholder: "MPIN कन्फर्म करें",
    mpinMismatch: "MPIN मेल नहीं खाते",
    mpinSetSuccess: "MPIN सेट! अगली बार इस्तेमाल करें।",
    mpinSetting: "सेट हो रहा है…",
    mpinSignInTitle: "MPIN से साइन इन करें",
    mpinSignInSubtitle: "फोन + MPIN (OTP की जरूरत नहीं)",
    mpinEnter: "MPIN डालें",
    mpinInvalid: "गलत फोन या MPIN",
    mpinSignIn: "MPIN से साइन इन करें",
    addToFavorites: "फेवरिट्स में जोड़ें",
    removeFromFavorites: "फेवरिट्स से हटाएं",
    orderSavedToHistory: "ऑर्डर आपके हिस्ट्री में सेव हो गया",
    welcomeBack: "वापसी पर स्वागत है!",
    customerOrders: "मेरे ऑर्डर",
    customerOrdersTitle: "आपके ऑर्डर",
    customerOrdersEmpty: "अभी कोई ऑर्डर नहीं",
    customerLogout: "लॉग आउट",
    customerWallet: "वॉलेट",
    walletBalance: "वॉलेट बैलेंस",
    redeemNow: "अभी रिडीम करें",
    recentTransactions: "हाल के ट्रांजैक्शन",
    noTransactions: "अभी कोई ट्रांजैक्शन नहीं",
    earnCoinsOnOrder: "हर ऑर्डर पर कॉइन कमाएं!",
    customerTransactions: "ट्रांजैक्शन",
    credit: "क्रेडिट",
    debit: "डेबिट",
    redemptionRequested: "रिडेम्प्शन अनुरोध हो गया!",
    redemptionPendingNote: "एडमिन जल्दी प्रोसेस करेंगे।",
    backToWallet: "वॉलेट पर वापस",
    selectRedemptionType: "रिडेम्प्शन टाइप चुनें",
    amountToRedeem: "रिडीम करने की रकम",
    availableBalance: "उपलब्ध",
    minCash100: "कैश के लिए न्यूनतम ₹100",
    minRedeem10: "न्यूनतम ₹10",
    submitRedemption: "जमा करें",
    back: "वापस",
    coinsEarned: "कॉइन मिले",
    congratulationsCoins: "बधाई हो! आपको {n} कॉइन मिले – वॉलेट में जोड़ दिए गए!",
    useWallet: "वॉलेट इस्तेमाल करें",
    walletAvailable: "₹{amount} उपलब्ध",
    searchTitle: "अपने पास दुकान खोजें",
    searchPlaceholder: "दुकान नाम, प्रकार या आइटम से खोजें (जैसे पानीपुरी, चाय, किराना)",
    searchZoneAll: "सभी जोन",
    searchZoneGeneral: "हैदराबाद",
    searchStallTypeAll: "सभी प्रकार",
    searchStallTypeKirana: "किराना / जनरल स्टोर",
    searchStallTypePanipuri: "पानी पुरी",
    searchStallTypeChai: "चाय",
    searchStallTypeTiffin: "टिफिन",
    searchStallTypePan: "पान",
    searchStallTypeFastFood: "फास्ट फूड",
    searchStallTypeSnacks: "स्नैक्स",
    searchStallTypeBeverage: "पेय",
    searchStallTypeFood: "खाना",
    searchStallTypeHardware: "हार्डवेयर दुकान",
    searchStallTypeSaloon: "सलून / स्पा",
    sortPopular: "सबसे लोकप्रिय",
    viewMenu: "मेन्यू देखें",
    searchVendorUnknown: "दुकानदार",
    searchOrdersLabel: "ऑर्डर",
    searchEmptyTitle: "कोई दुकानदार नहीं मिला",
    searchEmptySubtitle: "अपनी लोकल दुकान को haathpe में जोड़ने के लिए कहें!",
    searchFindVendors: "अपने पास दुकान खोजें",
    customerSignIn: "ग्राहक साइन इन",
    browseSuppliesForDukaan: "अपनी दुकान के लिए सप्लाई खरीदें",
    reviewModalTitle: "रेट और रिव्यू दें",
    reviewModalPlaceholder: "अपना अनुभव साझा करें (वैकल्पिक)",
    reviewModalCancel: "रद्द करें",
    reviewModalSubmit: "रिव्यू भेजें",
    reviewModalSubmitting: "भेज रहे हैं...",
    reviewStars: "सितारे",
    rateAndReview: "रेट और रिव्यू",
    statusPending: "ऑर्डर दिया",
    statusPrepared: "तैयार हो रहा है",
    statusReady: "पिकअप के लिए तैयार",
    statusDelivered: "डिलीवर हो गया",
    trackOrder: "ऑर्डर ट्रैक करें",
    orderId: "ऑर्डर आईडी",
    shareTracking: "ट्रैकिंग शेयर करें",
    deliveryPickup: "पिकअप",
    deliverySelf: "सेल्फ डिलीवरी",
    deliveryAddressPlaceholder: "डिलीवरी एड्रेस डालें",
    vendorWillDeliver: "दुकानदार डिलीवर करेगा (समय के लिए संपर्क करें)",
    customerReviews: "ग्राहक रिव्यू",
    averageRating: "औसत रेटिंग",
    noReviewsYet: "अभी कोई रिव्यू नहीं",
    sortRating: "टॉप रेटेड",
    searchUpsellSupplies: "प्लेट/कप चाहिए? सप्लाई खरीदें →",
    premiumUpgrade: "प्रीमियम अपग्रेड करें",
    premiumPrice: "₹99/महीना",
    premiumBenefits: "बूस्टेड सर्च, प्राथमिकता लिस्टिंग",
    premiumUpgradeCta: "अपग्रेड",
    zeroFeeMessage: "डिस्कवरी पर कोई कमीशन नहीं — केवल ONDC ऑर्डर पर 3% (PhonePe, Paytm आदि)",
    gstNote: "GST अलग से लागू",
    ondcExport: "कैटलॉग एक्सपोर्ट",
    ondcOrders: "ऑनलाइन ऑर्डर",
    ondcFeeNote: "ऑनलाइन ऑर्डर पर एडमिन द्वारा तय प्लेटफॉर्म फी लागू।",
    noOndcOrders: "अभी कोई ऑनलाइन ऑर्डर नहीं",
    onlineOrders: "ऑनलाइन ऑर्डर",
    catalogExport: "कैटलॉग एक्सपोर्ट",
    catalogExportTitle: "अपना मेन्यू एक्सपोर्ट करें",
    catalogExportDesc: "अपना मेन्यू JSON फाइल के रूप में डाउनलोड करें। ऑनलाइन ऑर्डर के लिए कैटलॉग सिंक करने में उपयोग करें।",
    catalogExportFutureTitle: "जल्द आ रहा है",
    catalogExportFutureDesc: "लाइव कैटलॉग सिंक और ऑटो अपडेट जल्द उपलब्ध होंगे।",
    onlineOrderFeeNote: "ऑनलाइन ऑर्डर पर एडमिन द्वारा तय प्लेटफॉर्म फी लागू।",
    noOnlineOrders: "अभी कोई ऑनलाइन ऑर्डर नहीं",
    newOnlineOrderToast: "नया ऑनलाइन ऑर्डर आया: ₹{amount} – तैयार करो!",
    orderSourceOnline: "ऑनलाइन",
    yourShare: "आपका हिस्सा",
    paid: "पेड",
    ondcEnabled: "ऑनलाइन ऑर्डर सक्षम",
    ondcMenuLive: "आपका मेन्यू ऑनलाइन ऑर्डर के लिए लाइव है!",
    upiPayoutHint: "ऑनलाइन ऑर्डर का तुरंत पेआउट के लिए (जैसे merchant@upi)",
    upiForPayout: "तुरंत पेआउट के लिए UPI",
    upiPlaceholder: "merchant@upi",
    dukaanType: "दुकान प्रकार",
    stallType: "स्टॉल प्रकार",
    dukaanAddress: "दुकान का पता",
    shopTimingsTitle: "दुकान समय और ऑनलाइन स्थिति",
    shopTimingsDesc: "घंटे, साप्ताहिक अवकाश, छुट्टियाँ सेट करें। ऑनलाइन ऑर्डर टॉगल करें।",
    editTimings: "समय संपादित करें",
    onlineOrdersAvailable: "ऑनलाइन ऑर्डर उपलब्ध",
    openTime: "खुलने का समय",
    closeTime: "बंद होने का समय",
    weeklyOff: "साप्ताहिक अवकाश",
    shopHolidays: "छुट्टियाँ (YYYY-MM-DD, एक पंक्ति में एक)",
    shopOpenNow: "आपकी दुकान अभी खुली है",
    shopClosedNow: "आपकी दुकान अभी बंद है",
    dukaanClosedTitle: "दुकान अभी बंद है",
    currentlyUnavailable: "वर्तमान में उपलब्ध नहीं",
    dashboardGreeting: "आपकी दुकान हाथ पे है",
    footerTagline: "haathpe – सब कुछ हाथ पे | डिस्कवरी पर कोई कमीशन नहीं",
    landingFeaturesNav: "फीचर्स",
    landingHowItWorksNav: "कैसे काम करता है",
    landingDukaanwaaleNav: "दुकानदार",
    signedInAs: "साइन इन हैं",
    logOut: "लॉग आउट",
    landingHeroPin: "किराना, चाय स्टॉल, हार्डवेयर और भी — हैदराबाद",
    landingHeroTagline: "आपकी दुकान, सरल",
    landingForEveryDukaan: "हर छोटी दुकान के लिए — किराना से सैलून तक",
    landingWhyLoveUs: "दुकानदार हमें क्यों पसंद करते हैं",
    landingWhyLoveUsDesc: "रोज़मर्रा के काम के लिए बना। सप्लाई ऑर्डर करें, क्रेडिट बनाएं, रिवॉर्ड कमाएं — सब अपने फोन से।",
    featureEasySupplies: "आसान सप्लाई",
    featureEasySuppliesDesc: "पेपर प्लेट, कप, माचिस — हैदराबाद में घंटों में आपकी दुकान पर पहुँचते हैं।",
    featureUnlockCredit: "क्रेडिट अनलॉक करें",
    featureUnlockCreditDesc: "20/30 दिन लगातार ऑर्डर करें और क्रेडिट लाइन अनलॉक करें ताकि स्टॉक कभी न खत्म हो।",
    featureEarnRedeem: "कमाएं और रिडीम करें",
    featureEarnRedeemDesc: "हर ऑर्डर पर लॉयल्टी पॉइंट्स कमाएं। फैमिली ट्रिप, कैश प्राइज़ और सप्लाई के लिए रिडीम करें।",
    buyBullet1: "थोक माचिस, प्लेट, चावल वगैरह",
    buyBullet2: "स्ट्रीक पर क्रेडिट अनलॉक",
    buyBullet3: "लॉयल्टी पॉइंट्स और ट्रिप कमाएं",
    buyBullet4: "हैदराबाद में तेज़ डिलीवरी",
    sellBullet1: "आपके दुकान टाइप के लिए रेडी डिफॉल्ट मेन्यू",
    sellBullet2: "दुकान पर तेज़ POS (कैश/UPI)",
    sellBullet3: "QR कोड से ऑनलाइन ऑर्डर",
    sellBullet4: "सेल्स, प्रॉफिट और री-ऑर्डर सुझाव ट्रैक करें",
    landingHowItWorksTitle: "कैसे काम करता है",
    landingHowItWorksSub: "सप्लाई, क्रेडिट और रिवॉर्ड के चार कदम।",
    step1Title: "साइन अप करें",
    step1Body: "फोन या ईमेल से एक मिनट में अपना दुकान अकाउंट बनाएं।",
    step2Title: "सप्लाई ऑर्डर करें",
    step2Body: "प्रोडक्ट ब्राउज़ करें, कार्ट में डालें और ऑर्डर दें। हैदराबाद में समान दिन डिलीवरी।",
    step3Title: "स्ट्रीक और क्रेडिट बनाएं",
    step3Body: "नियमित ऑर्डर करके स्ट्रीक बनाएं और अपनी दुकान के लिए क्रेडिट लाइन अनलॉक करें।",
    step4Title: "रिवॉर्ड कमाएं",
    step4Body: "पॉइंट्स जमा करें, डेली ड्रॉ में एंटर करें और वाउचर व प्राइज़ के लिए रिडीम करें।",
    faqCommonQuestions: "आम सवाल",
    faqWhoCanJoin: "haathpe में कौन जॉइन कर सकता है?",
    faqWhoCanJoinA: "हमारे सर्विस एरिया (हैदराबाद और विस्तार) का कोई भी छोटा रिटेलर या दुकानदार जॉइन कर सकता है। साइन अप के लिए फोन नंबर चाहिए। सप्लाई ऑर्डर शुरू करने के लिए GST या कागज़ात की जरूरत नहीं।",
    faqHowFastDelivery: "डिलीवरी कितनी तेज़ है?",
    faqHowFastDeliveryA: "सुबह दिए गए ऑर्डर के लिए हैदराबाद में समान दिन डिलीवरी। ऐप में ऑर्डर ट्रैक करें। आपके एरिया पर डिलीवरी स्लॉट निर्भर करता है — ज्यादातर दुकानदार कुछ घंटों में सप्लाई पाते हैं।",
    faqRedeemPoints: "मैं अपने पॉइंट्स किस चीज़ के लिए रिडीम कर सकता हूँ?",
    faqRedeemPointsA: "पॉइंट्स फैमिली ट्रिप, कैश प्राइज़, डेली ड्रॉ और सप्लाई के लिए रिडीम किए जा सकते हैं। ऑर्डरिंग स्ट्रीक बनाए रखने पर बेहतर क्रेडिट लिमिट और रिवॉर्ड भी मिलते हैं।",
    landingDukaanwaaleLikeYou: "आप जैसे दुकानदार",
    landingDukaanwaaleDesc: "हैदराबाद के चाय वालों, स्नैक विक्रेताओं और स्ट्रीट फूड हीरोज़ की असली कहानियाँ।",
    testimonial1Name: "राजू",
    testimonial1Stall: "चारमिनार के पास चाय दुकान",
    testimonial1Quote: "क्रेडिट लाइन ने रमज़ान से पहले स्टॉक करने में मदद की। अब रोज़ थोक वाले के पास नहीं जाना पड़ता।",
    testimonial2Name: "लक्ष्मी",
    testimonial2Stall: "स्नैक्स दुकान, सिकंदराबाद",
    testimonial2Quote: "पॉइंट्स से परिवार को तिरुपति ट्रिप मिली। यह ऐप जैसे रोज़ के काम के बोनस है।",
    testimonial3Name: "सुरेश",
    testimonial3Stall: "बेवरेज दुकान, गाचीबोवली",
    testimonial3Quote: "डिलीवरी तेज़ है। सुबह ऑर्डर दिया और दोपहर तक सप्लाई मिल गया। गेम चेंजर।",
    statsDukaanwaale: "दुकानदार",
    statsOrdersDelivered: "ऑर्डर डिलीवर",
    statsServingNow: "अभी सर्व कर रहे हैं",
    landingWhatYouCanOrder: "आप क्या ऑर्डर कर सकते हैं",
    landingWhatYouCanOrderDesc: "डिस्पोजेबल्स, जरूरी चीज़ें और दुकान के लिए रेडी किट।",
    productTeaser1: "🍽️ पेपर प्लेट और कप",
    productTeaser2: "🔥 माचिस और नैपकिन",
    productTeaser3: "🍵 चाय, चीनी और जरूरी चीज़ें",
    productTeaser4: "🎪 पानीपुरी और इको किट",
    landingReadyToGrow: "अपनी दुकान बढ़ाने के लिए तैयार?",
    landingJoinCta: "हैदराबाद के 1000+ दुकानदारों से जुड़ें। सप्लाई डिलीवर कराएं, क्रेडिट बनाएं और रिवॉर्ड कमाएं।",
    landingStartNow: "अभी शुरू करें",
    landingDashboardNav: "डैशबोर्ड",
    platformFeeLabel: "वर्तमान प्लेटफॉर्म फी",
    platformFeeExempt: "आप प्लेटफॉर्म फी से छूट प्राप्त हैं",
    platformFeeAdminNote: "एडमिन ऑनलाइन ऑर्डर के लिए फी तय करता है",
    platformFeeUpdated: "एडमिन ने प्लेटफॉर्म फी अपडेट कर दी",
  },
  te: {
    greeting: "నమస్తే",
    dashboard: "హోమ్",
    catalog: "ఉత్పత్తులు",
    catalogPageSubtitle: "మీ దుకాణానికి సరఫరా కొనడానికి",
    browseProducts: "ఉత్పత్తులు చూడండి",
    viewFullProducts: "అన్ని ఉత్పత్తులు చూడండి",
    browseProductsToOrder: "సరఫరా ఆర్డర్ చేయడానికి ఉత్పత్తులు చూడండి",
    orders: "కొనడం స్థలం",
    ordersPageSubtitle: "మీరు ఇచ్చిన సరఫరా ఆర్డర్లు",
    loyalty: "రివార్డ్స్",
    profile: "ప్రొఫైల్",
    cart: "కార్ట్",
    streak: "స్ట్రీక్",
    points: "పాయింట్లు",
    addToCart: "కార్ట్‌లో జోడించు",
    placeOrder: "ఆర్డర్ చేయండి",
    reorder: "మళ్ళీ ఆర్డర్",
    todayOrders: "నేటి ఆర్డర్లు",
    viewAll: "అన్నీ చూడండి",
    searchProducts: "ఉత్పత్తులు వెతకండి...",
    goodMorning: "శుభోదయం",
    goodAfternoon: "శుభ మద్యాహ్నం",
    goodEvening: "శుభ సాయంత్రం",
    creditWallet: "క్రెడిట్ వాలెట్",
    used: "ఉపయోగం",
    settings: "సెట్టింగ్‌లు",
    language: "భాష",
    notificationSettings: "నోటిఫికేషన్ సెట్టింగ్‌లు",
    viewNotifications: "నోటిఫికేషన్లు చూడండి",
    community: "కమ్యూనిటీ",
    vendorForum: "దుకాణదారుల ఫోరం",
    vendorSwap: "దుకాణ స్వాప్",
    upskillCourses: "అప్‌స్కిల్ కోర్సులు",
    logout: "లాగౌట్",
    editProfile: "ప్రొఫైల్ సవరించండి",
    manageAccount: "మీ ఖాతా మరియు ప్రాధాన్యతలను నిర్వహించండి",
    insuranceOptIn: "ఇన్సురెన్స్: మీ దుకాణకు ఆప్ట్-ఇన్ అందుబాటులో ఉంది",
    tier: "టైర్",
    default: "డిఫాల్ట్",
    sortPriceAsc: "ధర: తక్కువ నుండి ఎక్కువ",
    sortPriceDesc: "ధర: ఎక్కువ నుండి తక్కువ",
    sortName: "పేరు A–Z",
    all: "అన్నీ",
    essentials: "అవసరమైనవి",
    disposables: "డిస్పోజబుల్స్",
    electricals: "ఎలక్ట్రికల్స్",
    chipKirana: "కిరాణా",
    chipGeneral: "జనరల్",
    chipTeaStall: "టీ స్టాల్",
    chipPaniPuri: "పానీపూరీ",
    chipHardware: "హార్డ్వేర్",
    chipSaloon: "సాలూన్",
    kits: "కిట్లు",
    eco: "ఎకో",
    noOrders: "ఇంకా ఆర్డర్లు లేవు",
    profileUpdated: "ప్రొఫైల్ నవీకరించబడింది",
    saved: "సెట్టింగ్‌లు సేవ్ అయ్యాయి",
    addedToCart: "కార్ట్‌లో జోడించబడింది",
    orderPlaced: "ఆర్డర్ విజయవంతంగా ఇవ్వబడింది!",
    orderPlacedDraw: "ఆర్డర్ ఇవ్వబడింది! నేటి డ్రాలో మీరు ఎంటర్ అయ్యారు",
    markAllRead: "అన్నీ చదివినట్లు గుర్తించండి",
    noNotifications: "నోటిఫికేషన్లు లేవు",
    adminDashboard: "అడ్మిన్ డాష్‌బోర్డ్",
    admin: "అడ్మిన్",
    gst: "జీఎస్‌టీ",
    allSectors: "అన్ని సెక్టార్లు",
    inStock: "స్టాక్‌లో ఉంది",
    outOfStock: "స్టాక్ అయిపోయింది",
    subtotal: "ఉపమొత్తం",
    gstAmount: "జీఎస్‌టీ",
    total: "మొత్తం",
    discount: "తగ్గింపు",
    sales: "నా దుకాణం",
    mySalesMenu: "నా దుకాణం – మెనూ మరియు విక్రయాలు",
    activateDefault: "మీ దుకాణ రకానికి డిఫాల్ట్ మెనూ యాక్టివేట్ చేయండి",
    defaultPrice: "డిఫాల్ట్ ధర",
    yourPrice: "మీ ధర",
    save: "సేవ్",
    pos: "POS",
    cashPaid: "నగదు చెల్లించారు",
    generateUpiQr: "UPI QR జనరేట్ చేయండి",
    newOnlineOrder: "కొత్త ఆన్‌లైన్ ఆర్డర్!",
    salesPageSubtitle: "కస్టమర్లకు అమ్మండి – మెనూ, POS, ఆన్‌లైన్ ఆర్డర్లు",
    salesOverview: "విక్రయాల అవలోకనం",
    dailyRevenue: "ఈ రోజు రెవెన్యూ",
    topItems: "టాప్ ఐటమ్లు",
    grossProfit: "స్థూల లాభం",
    savingsThisWeek: "ఈ వారం పొదుపు",
    qrCodeMenu: "QR కోడ్ మెనూ",
    onlineMenu: "ఆన్‌లైన్ మెనూ",
    payOnline: "ఆన్‌లైన్ చెల్లించండి",
    payOnlineNow: "ఇప్పుడే ఆన్‌లైన్ చెల్లించండి",
    payAtDukaanWhenCollect: "తీసుకున్నప్పుడు దుకాణంలో చెల్లిస్తాను",
    tagline: "సబ్ కుచ్ హాథ్ పే",
    heroHeadline: "haathpe – ప్రతి చిన్న దుకాణానికి స్నేహితుడు",
    heroSubtitle: "కిరాణా నుండి టీ స్టాల్ వరకు – సరఫరా, విక్రయాలు, డబ్బు… అన్నీ చేతిలో",
    tileBuyBadge: "సరఫరా కొనండి",
    tileSellBadge: "కస్టమర్లకు అమ్మండి",
    tileBuyHeadline: "మీ దుకాణానికి స్టాక్ చేయండి",
    tileBuyCta: "నా దుకాణానికి సరఫరా కొనండి",
    tileBuyCtaLoggedIn: "సరఫరా కొనడానికి వెళ్లండి",
    tileBuyFooter: "ప్లేట్లు, టీ, కిరాణా – మీ దుకాణానికి స్టాక్ చేయండి",
    tileSellHeadline: "దుకాణం నడపండి మరియు అమ్మండి",
    tileSellCta: "నా దుకాణం తెరవండి (కస్టమర్లకు అమ్మండి)",
    tileSellCtaLoggedIn: "నా దుకాణానికి వెళ్లండి",
    tileSellFooter: "కస్టమర్లకు అమ్మండి – మెనూ, POS, ఆన్‌లైన్ ఆర్డర్లు",
    signIn: "సైన్ ఇన్",
    signUp: "సైన్ అప్",
    signInSignUp: "సైన్ ఇన్ / సైన్ అప్",
    myShop: "నా దుకాణం",
    dailyIncentives: "రోజువారీ ప్రోత్సాహకాలు",
    referralBonus: "రిఫరల్ బోనస్",
    inviteVendors: "దుకాణదారులను ఆహ్వానించండి",
    referralBonusDesc: "మీ లింక్ షేర్ చేయండి. రిఫర్ చేసిన దుకాణదారు 100 ఎంట్రీలు చేరినప్పుడు ₹100 సంపాదించండి.",
    copyLink: "లింక్ కాపీ చేయండి",
    withdraw: "విత్‌డ్రా",
    customerLoginTitle: "ఫోన్‌తో లాగిన్ చేయండి",
    customerLoginSubtitle: "ఫేవరిట్స్ సేవ్ చేయండి మరియు ఆర్డర్లను ట్రాక్ చేయండి",
    customerLoginPhone: "మొబైల్ నంబర్",
    customerLoginSendOtp: "OTP పంపండి",
    customerLoginOtpSent: "OTP పంపబడింది! మీ ఫోన్ చెక్ చేయండి.",
    customerLoginOtpSentTo: "కోడ్ పంపబడింది",
    customerLoginOtpCode: "6 అంకెల కోడ్ నమోదు చేయండి",
    customerLoginVerify: "ధృవీకరించండి",
    customerLoginVerifying: "ధృవీకరిస్తోంది…",
    customerLoginChangeNumber: "నంబర్ మార్చండి",
    customerLoginContinueGuest: "గెస్ట్‌గా కొనసాగించండి",
    customerLoginInvalidPhone: "చెల్లుబాటు అయ్యే 10 అంకెల నంబర్ నమోదు చేయండి",
    customerLoginError: "ఏదో తప్పు జరిగింది. మళ్ళీ ప్రయత్నించండి.",
    customerLoginSuccess: "మళ్ళీ స్వాగతం!",
    customerLoginBanner: "ఫేవరిట్స్ సేవ్ మరియు ఆర్డర్లను ట్రాక్ చేయడానికి ఫోన్‌తో లాగిన్ చేయండి",
    mpinCreateTitle: "4 అంకెల MPIN సృష్టించండి",
    mpinCreateSubtitle: "తర్వాత లాగిన్ చేయడానికి MPIN ఉపయోగించండి (OTP ఖర్చు తగ్గుతుంది)",
    mpinPlaceholder: "4 అంకెల MPIN నమోదు చేయండి",
    mpinConfirmPlaceholder: "MPIN నిర్ధారించండి",
    mpinMismatch: "MPINలు సరిపోలలేదు",
    mpinSetSuccess: "MPIN సెట్! తర్వాత ఉపయోగించండి।",
    mpinSetting: "సెట్ చేస్తోంది…",
    mpinSignInTitle: "MPINతో లాగిన్ చేయండి",
    mpinSignInSubtitle: "ఫోన్ + MPIN (OTP అవసరం లేదు)",
    mpinEnter: "MPIN నమోదు చేయండి",
    mpinInvalid: "తప్పు ఫోన్ లేదా MPIN",
    mpinSignIn: "MPINతో లాగిన్ చేయండి",
    addToFavorites: "ఫేవరిట్స్‌కు జోడించండి",
    removeFromFavorites: "ఫేవరిట్స్ నుండి తొలగించండి",
    orderSavedToHistory: "ఆర్డర్ మీ హిస్టరీలో సేవ్ అయ్యింది",
    welcomeBack: "మళ్ళీ స్వాగతం!",
    customerOrders: "నా ఆర్డర్లు",
    customerOrdersTitle: "మీ ఆర్డర్లు",
    customerOrdersEmpty: "ఇంకా ఆర్డర్లు లేవు",
    customerLogout: "లాగౌట్",
    customerWallet: "వాలెట్",
    walletBalance: "వాలెట్ బ్యాలెన్స్",
    redeemNow: "ఇప్పుడే రిడీమ్ చేయండి",
    recentTransactions: "ఇటీవలి లావాదేవీలు",
    noTransactions: "ఇంకా లావాదేవీలు లేవు",
    earnCoinsOnOrder: "ప్రతి ఆర్డర్‌లో కోయిన్‌లు సంపాదించండి!",
    customerTransactions: "లావాదేవీలు",
    credit: "క్రెడిట్",
    debit: "డెబిట్",
    redemptionRequested: "రిడెంప్షన్ అభ్యర్థించబడింది!",
    redemptionPendingNote: "అడ్మిన్ త్వరలో ప్రాసెస్ చేస్తారు.",
    backToWallet: "వాలెట్‌కు తిరిగి వెళ్లండి",
    selectRedemptionType: "రిడెంప్షన్ రకం ఎంచుకోండి",
    amountToRedeem: "రిడీమ్ చేయడానికి మొత్తం",
    availableBalance: "అందుబాటులో",
    minCash100: "నగదు కోసం కనీసం ₹100",
    minRedeem10: "కనీసం ₹10",
    submitRedemption: "సమర్పించండి",
    back: "వెనుక",
    coinsEarned: "కోయిన్‌లు సంపాదించారు",
    congratulationsCoins: "అభినందనలు! మీకు {n} కోయిన్‌లు వచ్చాయి – వాలెట్‌కు జోడించబడ్డాయి!",
    useWallet: "వాలెట్ ఉపయోగించండి",
    walletAvailable: "₹{amount} అందుబాటులో ఉంది",
    searchTitle: "మీ దగ్గర దుకాణను కనుగొనండి",
    searchPlaceholder: "దుకాణ పేరు, రకం లేదా ఐటమ్ ద్వారా వెతకండి (ఉదా. పానీపూరీ, చాయ్, కిరాణా)",
    searchZoneAll: "అన్ని జోన్లు",
    searchZoneGeneral: "హైదరాబాద్",
    searchStallTypeAll: "అన్ని రకాలు",
    searchStallTypeKirana: "కిరాణా దుకాణం",
    searchStallTypeGeneral: "జనరల్ స్టోర్",
    searchStallTypePanipuri: "పానీ పూరీ",
    searchStallTypeChai: "చాయ్ / టీ",
    searchStallTypeTiffin: "టిఫిన్",
    searchStallTypePan: "పాన్",
    searchStallTypeFastFood: "ఫాస్ట్ ఫుడ్",
    searchStallTypeSnacks: "స్నాక్స్",
    searchStallTypeBeverage: "పానీయాలు",
    searchStallTypeFood: "ఆహారం",
    searchStallTypeHardware: "హార్డ్వేర్ షాప్",
    searchStallTypeSaloon: "సాలూన్ / స్పా",
    sortPopular: "ఎక్కువ జనాదరణ",
    viewMenu: "మెనూ చూడండి",
    searchVendorUnknown: "దుకాణదారు",
    searchOrdersLabel: "ఆర్డర్లు",
    searchEmptyTitle: "దుకాణదారులు కనుగొనబడలేదు",
    searchEmptySubtitle: "మీ ప్రాంత దుకాణాన్ని haathpeలో చేరమని అడగండి!",
    searchFindVendors: "మీ దగ్గర దుకాణను కనుగొనండి",
    customerSignIn: "కస్టమర్ సైన్ ఇన్",
    browseSuppliesForDukaan: "మీ దుకాణకు సరఫరాలు కొనండి",
    reviewModalTitle: "రేట్ & రివ్యూ ఇవ్వండి",
    reviewModalPlaceholder: "మీ అనుభవాన్ని పంచుకోండి (ఐచ్ఛికం)",
    reviewModalCancel: "రద్దు చేయండి",
    reviewModalSubmit: "రివ్యూ సమర్పించండి",
    reviewModalSubmitting: "సమర్పిస్తోంది...",
    reviewStars: "నక్షత్రాలు",
    rateAndReview: "రేట్ & రివ్యూ",
    statusPending: "ఆర్డర్ ఇవ్వబడింది",
    statusPrepared: "సిద్ధం చేస్తోంది",
    statusReady: "పికప్ కు సిద్ధం",
    statusDelivered: "డెలివర్ అయింది",
    trackOrder: "ఆర్డర్ ట్రాక్ చేయండి",
    orderId: "ఆర్డర్ ఐడి",
    shareTracking: "ట్రాకింగ్ షేర్ చేయండి",
    deliveryPickup: "పికప్",
    deliverySelf: "సెల్ఫ్ డెలివరీ",
    deliveryAddressPlaceholder: "డెలివరీ చిరునామా నమోదు చేయండి",
    vendorWillDeliver: "దుకాణదారు డెలివర్ చేస్తారు (సమయానికి సంప్రదించండి)",
    customerReviews: "కస్టమర్ రివ్యూలు",
    averageRating: "సగటు రేటింగ్",
    noReviewsYet: "ఇంకా రివ్యూలు లేవు",
    sortRating: "టాప్ రేటెడ్",
    searchUpsellSupplies: "ప్లేట్లు/కప్పులు కావాలా? సరఫరా కొనండి →",
    premiumUpgrade: "ప్రీమియం అప్‌గ్రేడ్",
    premiumPrice: "₹99/నెల",
    premiumBenefits: "బూస్టెడ్ సెర్చ్, ప్రాధాన్యత లిస్టింగ్",
    premiumUpgradeCta: "అప్‌గ్రేడ్",
    zeroFeeMessage: "డిస్కవరీలో కమీషన్ లేదు — ONDC ఆర్డర్లపై మాత్రమే 3% (PhonePe, Paytm మొదలైనవి)",
    gstNote: "GST వర్తిస్తుంది",
    ondcExport: "కేటలాగ్ ఎక్స్‌పోర్ట్",
    ondcOrders: "ఆన్‌లైన్ ఆర్డర్లు",
    ondcFeeNote: "ఆన్‌లైన్ ఆర్డర్లకు అడ్మిన్ సెట్ చేసిన ప్లాట్‌ఫారమ్ ఫీ వర్తిస్తుంది.",
    noOndcOrders: "ఇంకా ఆన్‌లైన్ ఆర్డర్లు లేవు",
    onlineOrders: "ఆన్‌లైన్ ఆర్డర్లు",
    catalogExport: "కేటలాగ్ ఎక్స్‌పోర్ట్",
    catalogExportTitle: "మీ మెనూ ఎక్స్‌పోర్ట్ చేయండి",
    catalogExportDesc: "మీ మెనూ JSON ఫైల్‌గా డౌన్‌లోడ్ చేయండి. ఆన్‌లైన్ ఆర్డర్లకు కేటలాగ్ సింక్ చేయడానికి ఉపయోగించండి.",
    catalogExportFutureTitle: "త్వరలో వస్తోంది",
    catalogExportFutureDesc: "లైవ్ కేటలాగ్ సింక్ మరియు స్వయంచాలక నవీకరణలు త్వరలో అందుబాటులో ఉంటాయి.",
    onlineOrderFeeNote: "ఆన్‌లైన్ ఆర్డర్లకు అడ్మిన్ సెట్ చేసిన ప్లాట్‌ఫారమ్ ఫీ వర్తిస్తుంది.",
    noOnlineOrders: "ఇంకా ఆన్‌లైన్ ఆర్డర్లు లేవు",
    newOnlineOrderToast: "కొత్త ఆన్‌లైన్ ఆర్డర్ వచ్చింది: ₹{amount} – తయారు చేయండి!",
    orderSourceOnline: "ఆన్‌లైన్",
    yourShare: "మీ వంతు",
    paid: "చెల్లించారు",
    ondcEnabled: "ఆన్‌లైన్ ఆర్డర్లు ఎనేబుల్",
    ondcMenuLive: "మీ మెనూ ఆన్‌లైన్ ఆర్డర్లకు లైవ్!",
    upiPayoutHint: "ఆన్‌లైన్ ఆర్డర్ల తక్షణ పేఅవుట్ కోసం (ఉదా. merchant@upi)",
    upiForPayout: "తక్షణ పేఅవుట్ కోసం UPI",
    upiPlaceholder: "merchant@upi",
    dukaanType: "దుకాణ రకం",
    stallType: "స్టాల్ రకం",
    dukaanAddress: "దుకాణ చిరునామా",
    shopTimingsTitle: "దుకాణ సమయాలు మరియు ఆన్‌లైన్ స్థితి",
    shopTimingsDesc: "గంటలు, వారానికి సెలవు, సెలవులు సెట్ చేయండి. ఆన్‌లైన్ ఆర్డర్లను టాగిల్ చేయండి.",
    editTimings: "సమయాలను సవరించండి",
    onlineOrdersAvailable: "ఆన్‌లైన్ ఆర్డర్లు అందుబాటులో ఉన్నాయి",
    openTime: "తెరవే సమయం",
    closeTime: "మూసే సమయం",
    weeklyOff: "వారానికి సెలవు",
    shopHolidays: "సెలవులు (YYYY-MM-DD, ఒక్కొక్కటి ఒక లైన్)",
    shopOpenNow: "మీ దుకాణం ప్రస్తుతం తెరిచి ఉంది",
    shopClosedNow: "మీ దుకాణం ప్రస్తుతం మూసివేయబడింది",
    dukaanClosedTitle: "షాప్ ప్రస్తుతం మూసివేయబడింది",
    currentlyUnavailable: "ప్రస్తుతం అందుబాటులో లేదు",
    dashboardGreeting: "మీ దుకాణం చేతిలో ఉంది",
    footerTagline: "haathpe – సబ్ కుచ్ హాథ్ పే | డిస్కవరీలో కమీషన్ లేదు",
    landingFeaturesNav: "ఫీచర్లు",
    landingHowItWorksNav: "ఎలా పనిచేస్తుంది",
    landingDukaanwaaleNav: "దుకాణదారులు",
    signedInAs: "సైన్ ఇన్ అయ్యారు",
    logOut: "లాగౌట్",
    landingHeroPin: "కిరాణా, టీ స్టాల్, హార్డ్వేర్ మరియు మరిన్ని — హైదరాబాద్",
    landingHeroTagline: "మీ దుకాణం సులభతరం",
    landingForEveryDukaan: "ప్రతి చిన్న దుకాణానికి — కిరాణా నుండి సాలూన్ వరకూ",
    landingWhyLoveUs: "దుకాణదారులు మమ్మల్ని ఎందుకు ఇష్టపడతారు",
    landingWhyLoveUsDesc: "రోజువారీ పనులకు రూపొందించబడింది. సరఫరా ఆర్డర్ చేయండి, క్రెడిట్ నిర్మించండి, రివార్డ్లు సంపాదించండి — అన్నీ మీ ఫోన్ నుండి.",
    featureEasySupplies: "సులభ సరఫరాలు",
    featureEasySuppliesDesc: "పేపర్ ప్లేట్లు, కప్పులు, అగ్గిపెట్టెలు — హైదరాబాద్ అంతటా గంటల్లో మీ దుకాణానికి చేరుతాయి.",
    featureUnlockCredit: "క్రెడిట్ అన్‌లాక్ చేయండి",
    featureUnlockCreditDesc: "20/30 రోజులు వరుసగా ఆర్డర్ చేసి క్రెడిట్ లైన్లు అన్‌లాక్ చేయండి — స్టాక్ ఎప్పుడూ అయిపోవదు.",
    featureEarnRedeem: "సంపాదించండి మరియు రిడీమ్ చేయండి",
    featureEarnRedeemDesc: "ప్రతి ఆర్డర్‌లో లాయల్టీ పాయింట్లు సంపాదించండి. కుటుంబ ప్రయాణాలు, నగదు బహుమతులు మరియు సరఫరాలకు రిడీమ్ చేయండి.",
    buyBullet1: "వెసల్ అగ్గిపెట్టెలు, ప్లేట్లు, బియ్యం మొదలైనవి",
    buyBullet2: "స్ట్రీక్స్ మీద క్రెడిట్ అన్‌లాక్",
    buyBullet3: "లాయల్టీ పాయింట్లు మరియు ప్రయాణాలు సంపాదించండి",
    buyBullet4: "హైదరాబాద్‌లో ఫాస్ట్ డెలివరీ",
    sellBullet1: "మీ దుకాణ రకానికి రెడీ డిఫాల్ట్ మెనూ",
    sellBullet2: "దుకాణంలో త్వరిత POS (నగదు/UPI)",
    sellBullet3: "QR కోడ్ ద్వారా ఆన్‌లైన్ ఆర్డర్లు",
    sellBullet4: "విక్రయాలు, లాభాలు మరియు రీ-ఆర్డర్ సూచనలను ట్రాక్ చేయండి",
    landingHowItWorksTitle: "ఎలా పనిచేస్తుంది",
    landingHowItWorksSub: "సరఫరా, క్రెడిట్ మరియు రివార్డ్లకు నాలుగు అడుగులు.",
    step1Title: "సైన్ అప్ చేయండి",
    step1Body: "ఫోన్ లేదా ఇమెయిల్‌తో ఒక నిమిషంలో మీ దుకాణ ఖాతా సృష్టించండి.",
    step2Title: "సరఫరా ఆర్డర్ చేయండి",
    step2Body: "ఉత్పత్తులను బ్రౌజ్ చేయండి, కార్ట్‌కు జోడించండి మరియు ఆర్డర్ చేయండి. హైదరాబాద్‌లో అదే రోజు డెలివరీ.",
    step3Title: "స్ట్రీక్ మరియు క్రెడిట్ నిర్మించండి",
    step3Body: "మీ స్ట్రీక్ నిర్మించడానికి నియమితంగా ఆర్డర్ చేయండి మరియు మీ దుకాణానికి క్రెడిట్ లైన్లను అన్‌లాక్ చేయండి.",
    step4Title: "రివార్డ్లు సంపాదించండి",
    step4Body: "పాయింట్లను సంపాదించండి, రోజువారీ డ్రాలో ఎంటర్ చేయండి మరియు వౌచర్లు మరియు బహుమతుల కోసం రిడీమ్ చేయండి.",
    faqCommonQuestions: "సాధారణ ప్రశ్నలు",
    faqWhoCanJoin: "haathpeలో ఎవరు చేరవచ్చు?",
    faqWhoCanJoinA: "మా సర్వీస్ ఏరియా (హైదరాబాద్ మరియు విస్తరణ)లోని ఏ చిన్న రిటెయిలర్ లేదా దుకాణదారుకైనా చేరవచ్చు. సైన్ అప్ చేయడానికి ఫోన్ నంబర్ కావాలి. సరఫరా ఆర్డర్ చేయడం ప్రారంభించడానికి GST లేదా కాగితపు పని అవసరం లేదు.",
    faqHowFastDelivery: "డెలివరీ ఎంత త్వరగా వస్తుంది?",
    faqHowFastDeliveryA: "ఉదయం ఇచ్చిన ఆర్డర్లకు హైదరాబాద్ అంతటా అదే రోజు డెలివరీ అందిస్తాము. యాప్‌లో ఆర్డర్ ట్రాక్ చేయండి. మీ ప్రాంతం ఆధారంగా డెలివరీ స్లాట్లు — చాలా దుకాణదారులు కొన్ని గంటల్లోనే సరఫరా పొందుతారు.",
    faqRedeemPoints: "నా పాయింట్లను దేనికి రిడీమ్ చేయగలను?",
    faqRedeemPointsA: "పాయింట్లు కుటుంబ ప్రయాణాలు, నగదు బహుమతులు, రోజువారీ డ్రాలు మరియు సరఫరాలకు రిడీమ్ చేయబడతాయి. ఆర్డర్ స్ట్రీక్ నిర్వహిస్తే మంచి క్రెడిట్ లిమిట్లు మరియు రివార్డ్లు కూడా లభిస్తాయి.",
    landingDukaanwaaleLikeYou: "మీలాంటి దుకాణదారులు",
    landingDukaanwaaleDesc: "హైదరాబాద్ చాయ్ వాల్లు, స్నాక్స్ విక్రేతలు మరియు స్ట్రీట్ ఫుడ్ హీరోల నిజమైన కథలు.",
    testimonial1Name: "రాజు",
    testimonial1Stall: "చార్మినార్ దగ్గర టీ దుకాణం",
    testimonial1Quote: "క్రెడిట్ లైన్ రంజాన్ కు ముందు స్టాక్ చేయడంలో సహాయపడింది. ఇక రోజూ వెసల్ షాప్ వద్దకు పోవలసిన అవసరం లేదు.",
    testimonial2Name: "లక్ష్మీ",
    testimonial2Stall: "స్నాక్స్ దుకాణం, సికింద్రాబాద్",
    testimonial2Quote: "పాయింట్లు కుటుంబానికి తిరుపతి ప్రయాణం ఇచ్చాయి. ఇది నేను చేసే పనికి బోనస్ లాంటిది.",
    testimonial3Name: "సురేష్",
    testimonial3Stall: "బెవరేజ్ దుకాణం, గాచిబోవ్లి",
    testimonial3Quote: "డెలివరీ త్వరగా ఉంది. ఉదయం ఆర్డర్ చేస్తే మధ్యాహ్నానికే సరఫరా వస్తుంది. గేమ్ చేంజర్.",
    statsDukaanwaale: "దుకాణదారులు",
    statsOrdersDelivered: "డెలివర్ అయిన ఆర్డర్లు",
    statsServingNow: "ప్రస్తుతం సర్వ్ చేస్తున్నారు",
    landingWhatYouCanOrder: "మీరు ఏమి ఆర్డర్ చేయగలరు",
    landingWhatYouCanOrderDesc: "డిస్పోజబుల్స్, అవసరమైనవి మరియు మీ దుకాణానికి రెడీ-యుజ్ కిట్లు.",
    productTeaser1: "🍽️ పేపర్ ప్లేట్లు మరియు కప్పులు",
    productTeaser2: "🔥 అగ్గిపెట్టెలు మరియు నాప్కిన్లు",
    productTeaser3: "🍵 టీ, చక్కెర మరియు అవసరమైనవి",
    productTeaser4: "🎪 పానీపూరీ మరియు ఎకో కిట్లు",
    landingReadyToGrow: "మీ దుకాణం పెంచడానికి సిద్ధమా?",
    landingJoinCta: "హైదరాబాద్ 1000+ దుకాణదారులలో చేరండి. సరఫరా డెలివరీ చేయించండి, క్రెడిట్ నిర్మించండి మరియు రివార్డ్లు సంపాదించండి.",
    landingStartNow: "ఇప్పుడే ప్రారంభించండి",
    landingDashboardNav: "డాష్‌బోర్డ్",
    platformFeeLabel: "ప్రస్తుత ప్లాట్‌ఫారమ్ ఫీ",
    platformFeeExempt: "మీరు ప్లాట్‌ఫారమ్ ఫీ నుండి మినహాయింపు పొందారు",
    platformFeeAdminNote: "ఆన్‌లైన్ ఆర్డర్లకు అడ్మిన్ ఫీ నిర్ణయిస్తారు",
    platformFeeUpdated: "అడ్మిన్ ప్లాట్‌ఫారమ్ ఫీ నవీకరించారు",
  },
};

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof translations.en;

export function getProductDescription(p: Product, lang: Language): string {
  if (lang === "hi") return p.descriptionHi;
  if (lang === "te") return p.descriptionTe;
  return p.description;
}
